config/routes.rb
WpsLogger::Application.routes.draw do
  devise_for :users

  resources :maps

  resources :maps do
    resources :wifi_access_points do
      resources :wifi_logs
    end
    resources :movement_logs do
      get 'index'
      resources :wifi_logs
    end
    resources :wifi_logs
    resources :maps
  end

  resources :manual_locations

  resources :gps_locations

  resources :wifi_access_points

  root :to => "welcome#index"

end

app/models/wifi_access_point.rb
class WifiAccessPoint < ActiveRecord::Base
  has_many :wifi_logs
  belongs_to :manual_location

  class << self
    def find_or_initialize_by_json(json)
      self.find_or_initialize_by_ssid_and_mac(json.reject {|k, v| !self.attribute_method?(k)})
    end

#    def display_histgram(histgram, options = {})
#       Gnuplot.open do |gp|
#         Gnuplot::Plot.new(gp) do |plot|
#           if options[:terminal] =~ /(x11)|(aqua)/
#             plot.terminal options[:terminal]
#           else
#             plot.terminal options[:terminal]
#             plot.output options[:output]
#           end
#           plot.ticslevel 0
#           plot.set("size", "square")
#           plot.data << Gnuplot::DataSet.new([histgram.keys, histgram.keys.map {|i| histgram[i].size}]) do |ds|
#             ds.title = "histgram"
#           end
#         end
#       end
#    end

    def rssi_distance_vectors(options = {})
      wifi_access_points = WifiAccessPoint.where('manual_location_id IS NOT NULL')
      x = nil
      y = nil
      wifi_access_points.each do |ap|
        x_i, y_i = ap.rssi_distance_vectors(options)
        x = x.nil? ? x_i : x.concat(x_i)
        y = y.nil? ? y_i : y.concat(y_i)
      end
      p = x.sort_index
      p.permute(x)
      p.permute(y)
      [x, y]
    end

    def rssi_distance_graph(options = {})
      options = {
        :fit => :linear
      }.merge(options)
      target = self
      if !options[:wifi_access_point].nil?
        target = options[:wifi_access_point]
      end
      x, y = target.rssi_distance_vectors(options)
      return false if x.nil? || y.nil?
      sigma = GSL::Vector[x.size]
      sigma.set_all(0.1)
      case options[:fit]
      when :linear
        # linear power fit (log_10)
        # y = 10^{(A - x)/B}
        # log_10 y = (A - x)/B = A/B - 1/B * x
        # c0 = A/B, c1 = -1/B
        # the base conversion
        # when log_10 X = Y
        # then 10^Y = X
        # log_e 10^Y = log_e X
        # Y log_e 10 = log_e X
        # log_10 X = log_e X / log_e 10
        c0, c1, cov00, cov01, cov11, chisq, status = GSL::Fit.linear(x, GSL::Sf::log(y) / GSL::Sf::log(10))
        puts "c0: #{c0}"
        puts "c1: #{c1}"
        puts "y = e^(#{c0} + #{c1} * x)"
        x_lin = GSL::Vector.linspace(x.min, x.max, 40)
        # e^x = 10
        # log_e e^x = log_e 10
        # x = log_e 10
        # e^((log_e 10) * x) = (e^(log_e 10))^x = 10^x
        GSL::graph([x, y], [x_lin, GSL::Sf::exp(GSL::Sf::log(10) * (c0 + c1 * x_lin))], "-T X -C -S 2 -m 2")
      when :nonlinear
        # power fit
        coef, err, chi2, dof = GSL::MultiFit::FdfSolver.fit(-x, y, "power")
        # exp fit
        #coef, err, chi2, dof = GSL::MultiFit::FdfSolver.fit(x, sigma, y, "exponential")
        y0 = coef[0]
        amp = coef[1]
        b = coef[2]
        puts "y0: #{y0}"
        puts "amp: #{amp}"
        puts "b: #{b}"
        # power fit
        puts "#{y0} + #{amp} * GSL::pow(-x_lin, #{b})"
        # exp fit
        #puts "#{y0} + #{amp} * GSL::Sf::exp(#{-b} * x_lin)"
        x_lin = GSL::Vector.linspace(x.min, x.max, 40)
        # power fit
        GSL::graph([x, y], [x_lin, y0+amp*GSL::pow(-x_lin, b)], "-T X -C -S 2 -m 2")
        # exp fit
        #GSL::graph([x, y], [x_lin, y0+amp*GSL::Sf::exp(-b*x_lin)], "-T X -C -S 2 -m 2")
      end
    end
  end

  # Options are:
  # * <tt>:min</tt> - Minimum value of RSSI
  # * <tt>:max</tt> - Maximum value of RSSI
  # * <tt>:n</tt> - Number of bins
  # 
  # Example:
  #   h = WifiAccessPoint.find(10).generate_histogram
  #   # show graph in X11 window
  #   h.graph("-T X -C")
  def rssi_histogram(options = {})
    options = {
      :min => -100,
      :max => -30,
      :n => 7
    }.merge(options)
    min = options[:min]
    max = options[:max]
    n = options[:n]
    histogram = GSL::Histogram.alloc(n, [min, max])
    wifi_logs.each do |wifi_log|
      histogram.increment(wifi_log.signal)
    end
    histogram
  end

  # Options are:
  # * <tt>:wifi_logs</tt> - target wifi_logs
  def rssi_distance_vectors(options = {})
    return false if self.manual_location.nil?
    time_condition = ManualLocation.time_condition(options)
    logs = self.wifi_logs.where('movement_logs.manual_location_id IS NOT NULL').where(time_condition).all(:include => {:movement_log => :manual_location})
    x = GSL::Vector.alloc(logs.size)
    y = GSL::Vector.alloc(logs.size)
    logs.each_with_index do |wifi_log, i|
      x[i] = wifi_log.signal.to_f
      y[i] = Positioning::Base.haversine_distance(self.manual_location.geom, wifi_log.movement_log.manual_location.geom)
    end
    p = x.sort_index
    p.permute(x)
    p.permute(y)
    [x, y]
  end

  def rssi_distance_graph(options = {})
    options[:wifi_access_point] = self
    WifiAccessPoint.rssi_distance_graph(options)
  end
end

app/models/wps_logger/wifi_access_point.rb
class WpsLogger::WifiAccessPoint < WpsLogger::Base
  set_table_name :wifi_access_points

  has_many :wifi_logs
  belongs_to :manual_location

  class << self
    def find_or_initialize_by_json(json)
      self.find_or_initialize_by_ssid_and_mac(json.reject {|k, v| !self.attribute_method?(k)})
    end
  end
end

app/controllers/wifi_access_points_controller.rb
class WifiAccessPointsController < ApplicationController
  before_filter :authenticate_user!
  # GET /wifi_access_points/
  # GET /maps/1/wifi_access_points/
  # GET /maps/1/wifi_access_points.xml
  def index
    if !params["map_id"].nil?
      @map = Map.find(params["map_id"])
    end
    if @map.nil?
      @wifi_access_points = WifiAccessPoint.order("mac").all
    else
      @wifi_access_points = WifiAccessPoint.where('manual_locations.map_id = ?', params["map_id"]).order("mac").all(:include => [:manual_location])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @wifi_access_points }
    end
  end

  # GET /wifi_access_points/1
  # GET /wifi_access_points/1.xml
  def show
    @wifi_access_point = WifiAccessPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @wifi_access_point }
    end
  end

  # GET /wifi_access_points/new
  # GET /wifi_access_points/new.xml
  def new
    @wifi_access_point = WifiAccessPoint.new
    @manual_location = @wifi_access_point.manual_location

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @wifi_access_point }
    end
  end

  # GET /wifi_access_points/1/edit
  def edit
    @wifi_access_point = WifiAccessPoint.find(params[:id])
    @manual_location = @wifi_access_point.manual_location
  end

  # POST /wifi_access_points
  # POST /wifi_access_points.xml
  def create
    @wifi_access_point = WifiAccessPoint.new(params[:wifi_access_point])
    if !params[:manual_location].nil?
      @wifi_access_point.manual_location = ManualLocation.new(params[:manual_location])
    end
    respond_to do |format|
      if @wifi_access_point.save
        format.html { redirect_to(@wifi_access_point, :notice => 'WifiAccessPoint was successfully created.') }
        format.xml  { render :xml => @wifi_access_point, :status => :created, :location => @wifi_access_point }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @wifi_access_point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /wifi_access_points/1
  # PUT /wifi_access_points/1.xml
  def update
    @wifi_access_point = WifiAccessPoint.find(params[:id])
    @wifi_access_point.attributes = params[:wifi_access_point]
    if !params[:manual_location].nil?
      if @wifi_access_point.manual_location.nil?
        @wifi_access_point.manual_location = ManualLocation.new(params[:manual_location])
      else
        @manual_location = @wifi_access_point.manual_location
        @manual_location.attributes = params[:manual_location]
        @wifi_access_point.manual_location = @manual_location
      end
    end

    respond_to do |format|
      if @wifi_access_point.save
        #FIXME
        if @manual_location.nil?
          format.html { redirect_to(@wifi_access_point, :notice => 'WifiAccessPoint was successfully updated.') }
          format.xml  { head :ok }
        elsif @manual_location.save
          format.html { redirect_to(@wifi_access_point, :notice => 'WifiAccessPoint was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @wifi_access_point.errors, :status => :unprocessable_entity }
        end
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @wifi_access_point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /wifi_access_points/1
  # DELETE /wifi_access_points/1.xml
  def destroy
    @wifi_access_point = WifiAccessPoint.find(params[:id])
    @wifi_access_point.destroy

    respond_to do |format|
      format.html { redirect_to(wifi_access_points_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/wifi_access_points_helper.rb
module WifiAccessPointsHelper
end

app/views/wifi_access_points/_form.html.erb
<%= javascript_include_tag 'json2' %>
<%= javascript_include_tag 'map' %>
<%- if !@wifi_access_point.manual_location.nil? -%>
  <%- ml = @wifi_access_point.manual_location -%>
<script type="text/javascript">
  <!--
  // Global variables
  var map;
  var MAX_X = 800, MAX_Y = 640;

  window.onload = function () {
    var canvas = $('canvas');
    var curr_x = $('manual_location_x'), curr_y = $('manual_location_y');
    map = new Map('<%= compute_public_path(ml.map.image.url, '') %>',
        canvas,
        MAX_X,
        MAX_Y,
        <%= ml.x.nil? ? 0 : ml.x %>, <%= ml.y.nil? ? 0 : ml.y %>,
        curr_x, curr_y);
    map.draw();
    // Draw guide lines for mouse position
    canvas.observe('mousemove', map.drawWithLine.bind(map));
    canvas.observe('mouseout', map.drawWithoutLine.bind(map));
    // Update current position by mouse click
    canvas.observe('click', map.setCurrentPosition.bind(map));

    // Redraw current position when curr_x, curr_y values are updated
    curr_x.observe('change', map.changeValueX.bind(map));
    curr_y.observe('change', map.changeValueY.bind(map));
  };
-->
</script>
<canvas id="canvas" width="500" height="300"></canvas>
<%- end -%>
<div id="message"></div>
<div id="form">
<%= form_for(@wifi_access_point, :html => { :multipart => true}) do |f| %>
  <% if @wifi_access_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wifi_access_point.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @wifi_access_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ssid %><br />
    <%= f.text_field :ssid %>
  </div>
  <div class="field">
    <%= f.label :mac %><br />
    <%= f.text_field :mac %>
  </div>
  <%- ml = @wifi_access_point.manual_location -%>
  <div class="field">
    <table id="position_params">
      <tr>
        <td>x:</td>
        <td><%= text_field_tag('manual_location[x]', ml.nil? ? nil : ml.x, :size => 5) %></td>
        <td>y:</td>
        <td><%= text_field_tag('manual_location[y]', ml.nil? ? nil : ml.y, :size => 5) %></td>
      </tr>
      <tr>
        <td>height:</td>
        <td><%= text_field_tag('manual_location[height]', ml.nil? ? nil : ml.height, :size => 5) %></td>
        <td></td>
        <td></td>
      </tr>
    </table>
    <table id="step_params">
      <tr>
        <td>step_x:</td>
        <td><%= text_field_tag('manual_location[u_x]', '0', :size => 5) %></td>
        <td>step_y:</td>
        <td><%= text_field_tag('manual_location[u_y]', '0', :size => 5) %></td>
      </tr>
    </table>
  </div>
  <div class="field">
    <%= select('manual_location', 'map_id', Map.all.collect {|p| [p.name, p.id]}, {:include_blank => 'None'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/wifi_access_points/edit.html.erb
<h1>Editing WifiAccessPoint</h1>

<%= render 'form' %>

<div id="form_links">
<%= link_to 'Show', @wifi_access_point %> |
<%= link_to 'Back', wifi_access_points_path %>
</div>

app/views/wifi_access_points/index.html.erb
<h1>Listing WifiAccessPoint</h1>

<%- if !@map.nil? -%>
<%= javascript_include_tag 'json2' %>
<%= javascript_include_tag 'map' %>
<script type="text/javascript">
  <!--
  // Global variables
  var map;
  var MAX_X = 800, MAX_Y = 640;

  window.onload = function () {
    var canvas = $('canvas');
    map = new Map('<%= compute_public_path(@map.image.url, '') %>',
        canvas,
        MAX_X,
        MAX_Y,
        0, 0,
        0, 0,
        0, 0);
    map.drawStatic(function() {
    <%- @wifi_access_points.each do |wifi_access_point| -%>
      map.drawWifiAccessPoint(<%= wifi_access_point.manual_location.x %>,
        <%= wifi_access_point.manual_location.y %>);
    <%- end -%>
    });
  };
-->
</script>
<canvas id="canvas" width="500" height="300"></canvas>
<%- end -%>

<div id="wifi_access_points">
<table>
  <tr>
    <th>SSID</th>
    <th>MAC Address</th>
    <th>Map</th>
    <%- if !@map.nil? -%>
    <th colspan="3">Location</th>
    <th>Log</th>
    <%- end -%>
    <th colspan="3">Operation</th>
  </tr>

<% @wifi_access_points.each do |wifi_access_point| %>
  <tr>
    <td><%= wifi_access_point.ssid %></td>
    <td><%= wifi_access_point.mac %></td>
    <td><%= wifi_access_point.manual_location.nil? ? '' : link_to(wifi_access_point.manual_location.map.name, map_wifi_access_points_path(:map_id => wifi_access_point.manual_location.map_id)) %></td>
    <%- if !@map.nil? -%>
    <%-   if !wifi_access_point.manual_location.nil? -%>
    <td><%= wifi_access_point.manual_location.x %></td>
    <td><%= wifi_access_point.manual_location.y %></td>
    <td><%= wifi_access_point.manual_location.height %></td>
    <%-   else -%>
    <td></td>
    <td></td>
    <td></td>
    <%-   end -%>
    <td><%= link_to 'Show', map_wifi_access_point_wifi_logs_path(:map_id => @map.id, :wifi_access_point_id => wifi_access_point.id) %></td>
    <%- end -%>
    <td><%= link_to 'Show', wifi_access_point %></td>
    <td><%= link_to 'Edit', edit_wifi_access_point_path(wifi_access_point) %></td>
    <td><%= link_to 'Destroy', wifi_access_point, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>

<br />

<div class="clear">
<%= link_to 'New WifiAccessPoint', new_wifi_access_point_path %>
</div>

app/views/wifi_access_points/new.html.erb
<h1>New WifiAccessPoint</h1>

<%= render 'form' %>

<div id="form_links">
<%= link_to 'Back', wifi_access_points_path %>
</div>

app/views/wifi_access_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>SSID:</b>
  <%= @wifi_access_point.ssid %>
</p>

<p>
  <b>MAC Address:</b>
  <%= @wifi_access_point.mac %>
</p>

<%- if !@wifi_access_point.manual_location.nil? -%>
  <%- ml = @wifi_access_point.manual_location -%>
<p>
  <b>Map:</b>
  <%= ml.map.nil? ? '' : ml.map.name %>
</p>

<p>
  <b>x:</b>
  <%= ml.x %>
</p>

<p>
  <b>y:</b>
  <%= ml.y %>
</p>

<p>
  <b>height:</b>
  <%= ml.height %>
</p>
<%- end -%>

<%= link_to 'Edit', edit_wifi_access_point_path(@wifi_access_point) %> |
<%= link_to 'Back', wifi_access_points_path %>