config/routes.rb
WpsLogger::Application.routes.draw do
  devise_for :users

  resources :maps

  resources :maps do
    resources :wifi_access_points do
      resources :wifi_logs
    end
    resources :movement_logs do
      get 'index'
      resources :wifi_logs
    end
    resources :wifi_logs
    resources :maps
  end

  resources :manual_locations

  resources :gps_locations

  resources :wifi_access_points

  root :to => "welcome#index"

end

app/models/map.rb
class Map < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "320x320>", :thumb => "128x128>" }
  has_one :basis_map_relation, :foreign_key => 'relative_map_id', :class_name => 'MapRelation'
  has_many :relative_map_relations, :foreign_key => 'basis_map_id', :class_name => 'MapRelation'
  has_one :basis_map, :through => :basis_map_relation, :class_name => 'Map'
  has_many :relative_maps, :through => :relative_map_relations, :class_name => 'Map'
end

app/models/wps_logger/map.rb
class WpsLogger::Map < WpsLogger::Base
  set_table_name :maps

  has_attached_file :image, :styles => { :medium => "320x320>", :thumb => "128x128>" }
  has_one :basis_map_relation, :foreign_key => 'relative_map_id', :class_name => 'MapRelation'
  has_many :relative_map_relations, :foreign_key => 'basis_map_id', :class_name => 'MapRelation'
  has_one :basis_map, :through => :basis_map_relation, :class_name => 'Map'
  has_many :relative_maps, :through => :relative_map_relations, :class_name => 'Map'
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_filter :authenticate_user!
  # GET /maps
  # GET /maps/1/maps
  # GET /maps.xml
  def index
    if !params["map_id"].nil?
      @map = Map.find(params["map_id"])
    end
    @maps = Map.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1/maps/2
  # GET /maps/1.xml
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.xml
  def new
    @map = Map.new
    @maps = Map.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/1/edit
  def edit
    @map = Map.find(params[:id])
    @maps = Map.all
  end

  # POST /maps
  # POST /maps.xml
  def create
    if !params[:basis_map_relation].nil? && params[:basis_map_relation][:id] != '-1'
      @basis_map = Map.find(params[:basis_map_relation][:id])
    end
    @map = Map.new(params[:map])
    if !params[:use_gpsd_tpv].nil?
      gpsd_tpv = JSON.parse(params[:gpsd_tpv])
      @map.o_lat = gpsd_tpv["lat"]
      @map.o_lon = gpsd_tpv["lon"]
      @map.o_alt = gpsd_tpv["alt"]
    end
    if @basis_map.nil?
      if !@map.basis_map_relation.nil?
        @map.basis_map_relation.delete
      end
    else
      @map.basis_map = @basis_map
      @map.basis_map_relation.alt_diff = params[:basis_map_relation][:alt_diff]
      @map.basis_map_relation.brng_diff = params[:basis_map_relation][:brng_diff]
      @map.basis_map_relation.ref_x = params[:basis_map_relation][:ref_x]
      @map.basis_map_relation.ref_y = params[:basis_map_relation][:ref_y]
    end

    respond_to do |format|
      if @map.save
        format.html { redirect_to(@map, :notice => 'Map was successfully created.') }
        format.xml  { render :xml => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.xml
  def update
    @map = Map.find(params[:id])
    # update instance
    @map.attributes = params[:map]
    if !params[:use_gpsd_tpv].nil?
      gpsd_tpv = JSON.parse(params[:gpsd_tpv])
      @map.o_lat = gpsd_tpv["lat"]
      @map.o_lon = gpsd_tpv["lon"]
      @map.o_alt = gpsd_tpv["alt"]
    end
    if !params[:basis_map_relation].nil? && params[:basis_map_relation][:id] != '-1'
      @basis_map = Map.find(params[:basis_map_relation][:id])
    end
    if @basis_map.nil?
      if !@map.basis_map_relation.nil?
        @map.basis_map_relation.delete
      end
    else
      @map.basis_map = @basis_map
      @map.basis_map_relation.alt_diff = params[:basis_map_relation][:alt_diff]
      @map.basis_map_relation.brng_diff = params[:basis_map_relation][:brng_diff]
      @map.basis_map_relation.ref_x = params[:basis_map_relation][:ref_x]
      @map.basis_map_relation.ref_y = params[:basis_map_relation][:ref_y]
    end

    respond_to do |format|
      if @map.save && (@map.basis_map_relation.nil? ||
                       (!@map.basis_map_relation.nil? &&
                        @map.basis_map_relation.save))
        format.html { redirect_to(@map, :notice => 'Map was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.xml
  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    respond_to do |format|
      format.html { redirect_to(maps_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= javascript_include_tag 'json2' %>
<%= javascript_include_tag 'map' %>
<script type="text/javascript">
  <!--
  // Global variables
  var map;
  var MAX_X = 800, MAX_Y = 640;

  window.onload = function () {
    var canvas = $('canvas');
    var map_o_x = $('map_o_x'), map_o_y = $('map_o_y');
    map = new Map('<%= compute_public_path(@map.image.url, '') %>',
        canvas,
        MAX_X,
        MAX_Y,
        <%= @map.o_x %>, <%= @map.o_y %>,
        map_o_x, map_o_y);
    map.draw();
    // Draw guide lines for mouse position
    canvas.observe('mousemove', map.drawWithLine.bind(map));
    canvas.observe('mouseout', map.drawWithoutLine.bind(map));
    // Update current position by mouse click
    canvas.observe('click', map.setCurrentPosition.bind(map));

    // Redraw current position when curr_x, curr_y values are updated
    map_o_x.observe('change', map.changeValueX.bind(map));
    map_o_y.observe('change', map.changeValueY.bind(map));
  };
-->
</script>
<canvas id="canvas" width="500" height="300"></canvas>
<div id="message"></div>
<div id="form">
<%= form_for(@map, :html => { :multipart => true}) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :o_lat %><br />
    <%= f.text_field :o_lat %>
  </div>
  <div class="field">
    <%= f.label :o_lon %><br />
    <%= f.text_field :o_lon %>
  </div>
  <div class="field">
    <%= f.label :o_alt %><br />
    <%= f.text_field :o_alt %>
  </div>
  <div class="field">
    <%= label_tag :gpsd_tpv %><br />
    <%= text_area_tag :gpsd_tpv %><br />
    <%= check_box_tag :use_gpsd_tpv %>Use GPSD TPV to set position<br />
  </div>
  <div class="field">
    <%= f.label :brng %><br />
    <%= f.text_field :brng %>
  </div>
  <div class="field">
    <%= f.label :o_x %><br />
    <%= f.text_field :o_x %>
  </div>
  <div class="field">
    <%= f.label :o_y %><br />
    <%= f.text_field :o_y %>
  </div>
  <div class="field">
    <%= f.label :dist_pix_ratio %><br />
    <%= f.text_field :dist_pix_ratio %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :basis_map_relation %><br />
    <%- @maps.each do |map| -%>
      <%- next if @map == map -%>
    <%= radio_button_tag 'basis_map_relation[id]', map.id, (@map.basis_map == map) %><%= map.name %><br />
    <%- end -%>
    <%= radio_button_tag 'basis_map_relation[id]', -1, @map.basis_map.nil? %>Use absolute position<br />
    <table>
      <tr>
        <td>Altitude difference</td>
        <td><%= text_field_tag('basis_map_relation[alt_diff]', @map.basis_map_relation.nil? ? '' : @map.basis_map_relation.alt_diff, :size => 10) %></td>
      </tr>
      <tr>
        <td>Bearing difference</td>
        <td><%= text_field_tag('basis_map_relation[brng_diff]', @map.basis_map_relation.nil? ? '' : @map.basis_map_relation.brng_diff, :size => 10) %></td>
      </tr>
      <tr>
        <td>Reference x-coordinate</td>
        <td><%= text_field_tag('basis_map_relation[ref_x]', @map.basis_map_relation.nil? ? '' : @map.basis_map_relation.ref_x, :size => 10) %></td>
      </tr>
      <tr>
        <td>Reference y-coordinate</td>
        <td><%= text_field_tag('basis_map_relation[ref_y]', @map.basis_map_relation.nil? ? '' : @map.basis_map_relation.ref_y, :size => 10) %></td>
      </tr>
    </table>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<div id="form_links">
<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>
</div>

app/views/maps/index.html.erb
<h1>Listing maps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th colspan="2">Log</th>
    <th>WifiAccessPoint</th>
    <th>MovementLog</th>
    <th colspan="3">Operation</th>
  </tr>

<% @maps.each do |map| %>
  <tr>
    <td><%=h map.name %></td>
    <td><%= image_tag map.image.url(:thumb) %></td>
    <td><%= link_to 'Show', map_wifi_logs_path(map) %></td>
    <td><%= link_to 'New', new_map_wifi_log_path(map) %></td>
    <td><%= link_to 'Show', map_wifi_access_points_path(map) %></td>
    <td><%= link_to 'Show', map_movement_logs_path(map) %></td>
    <td><%= link_to 'Show', map %></td>
    <td><%= link_to 'Edit', edit_map_path(map) %></td>
    <td><%= link_to 'Destroy', map, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<div class="clear">
<%= link_to 'New Map', new_map_path %>
</div>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<div id="form_links">
<%= link_to 'Back', maps_path %>
</div>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @map.name %>
</p>

<p>
  <b>Origin latitude:</b>
  <%= @map.o_lat %>
</p>

<p>
  <b>Origin longitude:</b>
  <%= @map.o_lon %>
</p>

<p>
  <b>Origin altitude:</b>
  <%= @map.o_alt %>
</p>

<p>
  <b>Origin x (pixel):</b>
  <%= @map.o_x %>
</p>

<p>
  <b>Origin y (pixel):</b>
  <%= @map.o_y %>
</p>

<p>
  <b>Bearing (rad):</b>
  <%= @map.brng %>
</p>

<p>
  <b>Distance/Pixel ratio:</b>
  <%= @map.dist_pix_ratio %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @map.image.url %>
</p>

<p>
  <b>Description:</b>
  <%= @map.description %>
</p>

<p>
  <b>Basis map:</b>
  <%- if @map.basis_map.nil? -%>
    'Use absolute position'
  <%- else -%>
    <%= @map.basis_map.name %>, <%= @map.basis_map_relation.alt_diff %>m, (<%= @map.basis_map_relation.ref_x %>, <%= @map.basis_map_relation.ref_y %>)
  <%- end -%>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>