config/routes.rb
WpsLogger::Application.routes.draw do
  devise_for :users

  resources :maps

  resources :maps do
    resources :wifi_access_points do
      resources :wifi_logs
    end
    resources :movement_logs do
      get 'index'
      resources :wifi_logs
    end
    resources :wifi_logs
    resources :maps
  end

  resources :manual_locations

  resources :gps_locations

  resources :wifi_access_points

  root :to => "welcome#index"

end

app/models/wifi_log.rb
class WifiLog < ActiveRecord::Base
  belongs_to :wifi_access_point
  belongs_to :movement_log

  class << self
    def new_by_json(json)
      self.new(json.reject {|k, v| !self.attribute_method?(k)})
    end

    def signal_condition(options = {})
      # parameter format
      # signal=-79
      if options[:signal].nil?
        condition = {}
      else
        condition = ['wifi_logs.signal = ?', options[:signal].to_i]
      end
      condition
    end
  end
end

app/models/wps_logger/wifi_log.rb
class WpsLogger::WifiLog < WpsLogger::Base
  set_table_name :wifi_logs

  belongs_to :wifi_access_point
  belongs_to :movement_log

  class << self
    def new_by_json(json)
      self.new(json.reject {|k, v| !self.attribute_method?(k)})
    end
  end
end

app/controllers/wifi_logs_controller.rb
class WifiLogsController < ApplicationController
  before_filter :authenticate_user!
  # GET /maps/1/wifi_logs/
  # GET /maps/1/wifi_access_points/1/wifi_logs/
  # GET /maps/1/movement_logs/1/wifi_logs/
  def index
    if !params[:map_id].nil?
      @map = Map.find(params[:map_id])
    else
      #FIXME
    end

    if !params[:wifi_access_point_id].nil?
      @wifi_access_point = WifiAccessPoint.find(params[:wifi_access_point_id])
    elsif !params[:movement_log_id].nil?
      @movement_log = MovementLog.find(params[:movement_log_id])
    else
      #FIXME
    end

    time_condition = ManualLocation.time_condition(params)
    signal_condition = WifiLog.signal_condition(params)

    if @movement_log.nil?
      @manual_locations = ManualLocation.where(:map_id => @map.id).where(time_condition)
      @wifi_logs = []
      @wifi_access_points = []
      @manual_locations.each do |l|
        if !l.movement_log.nil?
          if @wifi_access_point.nil? && @movement_log.nil?
            @wifi_logs += l.movement_log.wifi_logs.where('manual_locations.map_id = ?', @map.id).where(signal_condition).order('wifi_access_points.mac').all(:include => {:wifi_access_point => :manual_location})
            @wifi_access_points += l.movement_log.wifi_access_points.where('manual_locations.map_id = ?', @map.id).where(signal_condition).all(:include => :manual_location)
          else
            @wifi_logs += l.movement_log.wifi_logs.where(:wifi_access_point_id => @wifi_access_point.id).where(signal_condition)
          end
        end
      end
      @wifi_access_points = @wifi_access_points.uniq
    else
      @wifi_logs = @movement_log.wifi_logs.where(signal_condition).order('wifi_access_points.mac').all(:include => :wifi_access_point)
      @wifi_access_points = @movement_log.wifi_access_points.where('wifi_access_points.manual_location_id IS NOT NULL').where('manual_locations.map_id = ?', @movement_log.manual_location.map.id).where(signal_condition).all(:include => :manual_location)
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /wifi_access_points/1
  # GET /maps/1/wifi_access_points/1/wifi_logs/1
  # GET /maps/1/movement_logs/1/wifi_logs/1
  def show
    if !params[:map_id].nil?
      @map = Map.find(params[:map_id])
    end
    if !params[:wifi_access_point_id].nil?
      @wifi_access_point = WifiAccessPoint.find(params[:wifi_access_point_id])
    elsif !params[:movement_log_id].nil?
      @movement_log = MovementLog.find(params[:movement_log_id])
    else
      #FIXME
    end
    @wifi_log = WifiLog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @wifi_log }
    end
  end

  # GET /maps/1/wifi_logs/new
  def new
    @wifi_log = WifiLog.new
    if !params[:map_id].nil?
      @map = Map.find(params[:map_id])
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @wifi_log }
    end
  end

  # POST /maps/1/wifi_logs
  def create
    begin
      WifiLog.transaction do
        @manual_location = ManualLocation.new
        @manual_location.init_by_params(params)
        @manual_location.save!

        @gpsd_tpv = nil
        @gps_location = nil
        if !params["gpsd_tpv"].nil? && !params["gpsd_tpv"].empty?
          @gpsd_tpv = JSON.parse(params["gpsd_tpv"])
          if !@gpsd_tpv.empty?
            @gps_location = GpsLocation.new_by_json(@gpsd_tpv)
            @gps_location.save!
          end
        end
        @movement_log = MovementLog.new
        @movement_log.manual_location = @manual_location
        @movement_log.gps_location = @gps_location
        # FIXME
        # how to specify current user in Devise
        @movement_log.user = current_user
        @movement_log.remote_addr = request.remote_addr
        @movement_log.user_agent = request.user_agent
        @movement_log.user_device = params["user_device"]
        @movement_log.save!

        if !params["wifi_towers"].nil? && !params["wifi_towers"].empty?
          @wifi_towers = JSON.parse(params["wifi_towers"])
          @wifi_towers.each do |wifi_tower|
            @wifi_access_point = WifiAccessPoint.find_or_initialize_by_json(wifi_tower)
            if !@wifi_access_point.persisted?
              @wifi_access_point.save!
            end
            @wifi_log = WifiLog.new_by_json(wifi_tower)
            @wifi_log.wifi_access_point = @wifi_access_point
            @wifi_log.movement_log = @movement_log
            @wifi_log.save!
          end
        end
      end
      respond_to do |format|
        format.html { render :text => "Logs are successfully recorded." }
      end
    rescue
      respond_to do |format|
        format.html { render :text => "Failed to record logs." }
      end
    end
  end

  # DELETE /wifi_logs/1
  # DELETE /maps/1/wifi_access_point/1/wifi_logs/1
  def destroy
    @wifi_log = WifiLog.find(params[:id])
    @wifi_log.destroy

    respond_to do |format|
      format.html do
        if !params[:map_id].nil? && !params[:wifi_access_point_id].nil?
          redirect_to(map_wifi_access_point_wifi_logs_url(:map_id => params[:map_id], :wifi_access_point_id => params[:wifi_access_point_id]))
        else
          redirect_to(wifi_logs_url)
        end
      end
      format.xml  { head :ok }
    end
  end
end

app/helpers/wifi_logs_helper.rb
module WifiLogsHelper
end

app/views/wifi_logs/index.html.erb
<h1>Recorded logs</h1>

<%= javascript_include_tag 'json2' %>
<%= javascript_include_tag 'map' %>
<script type="text/javascript">
  <!--
  // Global variables
  var map;
  var MAX_X = 800, MAX_Y = 640;

  window.onload = function () {
    var canvas = $('canvas');
    map = new Map('<%= compute_public_path(@map.image.url, '') %>',
        canvas,
        MAX_X,
        MAX_Y,
        0, 0,
        0, 0,
        0, 0);
    map.drawStatic(function() {
    <%- @wifi_logs.each do |wifi_log| -%>
      map.drawWifiLog(<%= wifi_log.movement_log.manual_location.x %>,
        <%= wifi_log.movement_log.manual_location.y %>,
        <%= wifi_log.signal %>);
    <%- end -%>
    <%- @wifi_access_points.each do |wifi_ap| -%>
      <%- next if wifi_ap.manual_location.nil? -%>
      map.drawWifiAccessPoint(<%= wifi_ap.manual_location.x %>,
        <%= wifi_ap.manual_location.y %>);
    <%- end -%>
    <%- if !@wifi_access_point.nil? && !@wifi_access_point.manual_location.nil? -%>
      map.drawWifiAccessPoint(<%= @wifi_access_point.manual_location.x %>,
        <%= @wifi_access_point.manual_location.y %>);
    <%- end -%>
    <%- if !@movement_log.nil? -%>
      map.drawMovementLog(<%= @movement_log.manual_location.x %>,
        <%= @movement_log.manual_location.y %>);
    <%- end -%>
    });
  };
-->
</script>
<canvas id="canvas" width="500" height="300"></canvas>
<%- if !@map.nil? && (!@wifi_access_point.nil? || !@movement_log.nil?) -%>
<!-- wifi_logs related to a wifi_access_point -->
<div id="wifi_logs">
<table>
  <tr>
    <th colspan="2">WifiAccessPoint</th>
    <th colspan="2">Devise</th>
    <th colspan="4">Location</th>
    <th>Signal</th>
    <th colspan="2">Operation</th>
  </tr>
<%- @wifi_logs.each do |wifi_log| -%>
  <tr>
    <td><%= link_to wifi_log.wifi_access_point.mac, map_wifi_access_point_wifi_logs_path(:map_id => @map.id, :wifi_access_point_id => wifi_log.wifi_access_point.id)  %></td>
    <td><%= wifi_log.wifi_access_point.manual_location.nil? ? '' : wifi_log.wifi_access_point.manual_location.map.name %></td>
    <td><%= wifi_log.movement_log.user.email %></td>
    <td><%= wifi_log.movement_log.user_agent %></td>
    <td><%= wifi_log.movement_log.manual_location.x %></td>
    <td><%= wifi_log.movement_log.manual_location.y %></td>
    <td><%= wifi_log.movement_log.manual_location.height %></td>
    <td><%= Time.at(wifi_log.movement_log.manual_location.time/1000) %></td>
    <%- if !@wifi_access_point.nil? -%>
    <td><%= link_to wifi_log.signal, map_wifi_access_point_wifi_logs_path(:map_id => @map.id, :wifi_access_point_id => @wifi_access_point.id, :signal => wifi_log.signal) %></td>
    <td><%= link_to 'Show', map_wifi_access_point_wifi_log_path(:map_id => @map.id, :wifi_access_point_id => @wifi_access_point.id, :id => wifi_log.id) %></td>
    <td><%= link_to 'Destroy', map_wifi_access_point_wifi_log_path(:map_id => @map.id, :wifi_access_point_id => @wifi_access_point.id, :id => wifi_log.id), :confirm => 'Are you sure?', :method => :delete %></td>
    <%- elsif !@movement_log.nil? %>
    <td><%= link_to wifi_log.signal, map_movement_log_wifi_logs_path(:map_id => @map.id, :movement_log_id => @movement_log.id, :signal => wifi_log.signal) %></td>
    <td><%= link_to 'Show', map_movement_log_wifi_log_path(:map_id => @map.id, :movement_log_id => @movement_log.id, :id => wifi_log.id) %></td>
    <td><%= link_to 'Destroy', map_movement_log_wifi_log_path(:map_id => @map.id, :movement_log_id => @movement_log.id, :id => wifi_log.id), :confirm => 'Are you sure?', :method => :delete %></td>
    <%- else -%>
    <!-- FIXME -->
    <%- end -%>
  </tr>
<%- end -%>
</table>
</div>
<%- end -%>
<!--
<div id="wifi_access_points">
<%- @wifi_access_points.each do |wifi_ap| -%>
  <%= link_to("#{wifi_ap.ssid} (#{wifi_ap.mac})", url_for(:controller => "wifi_logs", :action => "index", :map_id => @map.id, :wifi_access_point_id => wifi_ap.id, :before => params[:before], :after => params[:after])) %><br/>
<%- end -%>
</div>
-->
<div class="clear">
<%- if @map.nil? -%>
<%= link_to 'Back', maps_path %>
<%- elsif !@map.nil? && !@wifi_access_point.nil? -%>
<%= link_to 'Back', map_wifi_access_points_path(:map_id => @map.id) %>
<%- elsif !@map.nil? && !@movement_log.nil? %>
<%= link_to 'Back', map_movement_logs_path(:map_id => @map.id) %>
<%- end -%>
</div>

app/views/wifi_logs/new.html.erb
<h1>Register logs</h1>

<%= javascript_include_tag 'json2' %>
<%= javascript_include_tag 'map' %>
<script type="text/javascript">
  <!--
  // Global variables
  var map;
  var MAX_X = 800, MAX_Y = 640;

  window.onload = function () {
    var canvas = $('canvas');
    var curr_x = $('curr_x'), curr_y = $('curr_y');
    map = new Map('<%= compute_public_path(@map.image.url, '') %>',
        canvas,
        MAX_X,
        MAX_Y,
        0, 0,
        curr_x, curr_y,
        $('step_x'), $('step_y'));
    map.draw();
    // Draw guide lines for mouse position
    canvas.observe('mousemove', map.drawWithLine.bind(map));
    canvas.observe('mouseout', map.drawWithoutLine.bind(map));
    // Update current position by mouse click
    canvas.observe('click', map.setCurrentPosition.bind(map));

    // Redraw current position when curr_x, curr_y values are updated
    curr_x.observe('change', map.changeValueX.bind(map));
    curr_y.observe('change', map.changeValueY.bind(map));

    // Move current position to the specified direction by step value
    $('up_button').observe('click', map.moveUp.bind(map));
    $('left_button').observe('click', map.moveLeft.bind(map));
    $('right_button').observe('click', map.moveRight.bind(map));
    $('down_button').observe('click', map.moveDown.bind(map));
    $('submit').observe('click', function(event) { $('time').value = new Date.now(); });
    $('form').observe('ajax:success', function(event) {
      message = $('message');
      message.update(event.memo.responseText + '<br/>at ' + new Date().toLocaleString());
      //message.insert(event.memo.responseText);
      message.style.color = "green";
    });
    $('form').observe('ajax:failure', function(event) {
      message = $('message');
      message.update(event.memo.responseText + '<br/>at ' + new Date().toLocaleString());
      //message.insert(event.memo.responseText);
      message.style.color = "red";
    });
  };
-->
</script>
<canvas id="canvas" width="500" height="300"></canvas>
<div id="message"></div>
<div id="form">
  <table id="position_controller">
    <tr>
      <td></td>
      <td><button id="up_button">Up</button></td>
      <td></td>
    </tr>
    <tr>
      <td><button id="left_button">Left</button></td>
      <td></td>
      <td><button id="right_button">Right</button></td>
    </tr>
    <tr>
      <td></td>
      <td><button id="down_button">Down</button></td>
      <td></td>
    </tr>
  </table>
  <%= form_tag(map_wifi_logs_path(@map), :remote => true) %>
    <table id="step_params">
      <tr>
        <td>step_x:</td>
        <td><%= text_field_tag('step_x', '1', :size => 5) %></td>
        <td>step_y:</td>
        <td><%= text_field_tag('step_y', '1', :size => 5) %></td>
      </tr>
    </table>
    <table id="position_params">
      <tr>
        <td>curr_x:</td>
        <td><%= text_field_tag('curr_x', nil, :size => 5) %></td>
        <td>curr_y:</td>
        <td><%= text_field_tag('curr_y', nil, :size => 5) %></td>
      </tr>
      <tr>
        <td>height:</td>
        <td><%= text_field_tag('height', nil, :size => 5) %></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td colspan="2">user device:</td>
        <td colspan="2"><%= text_field_tag('user_device', nil, :size => 15) %></td>
      </tr>
    </table>
    <table id="wifi_tower_params">
      <tr>
        <td>wifi_towers:</td>
      </tr>
      <tr>
        <td><%= text_area_tag('wifi_towers', nil, :size => "20x3") %></td>
      </tr>
      <tr>
        <td>gpsd_tpv:</td>
      </tr>
      <tr>
        <td><%= text_area_tag('gpsd_tpv', nil, :size => "20x3") %></td>
      </tr>
    </table>
    <table id="buttons">
      <tr>
        <td><%= submit_tag('Save', :id => 'submit') %></td>
        <td><%= link_to('Back', maps_path) %></td>
      </tr>
    </table>
    <%= hidden_field_tag('time') %>
  </form>
</div>

app/views/wifi_logs/show.html.erb
<h1>Recorded log</h1>

<%- if !@map.nil? -%>
<%= javascript_include_tag 'json2' %>
<%= javascript_include_tag 'map' %>
<script type="text/javascript">
  <!--
  // Global variables
  var map;
  var MAX_X = 800, MAX_Y = 640;

  window.onload = function () {
    var canvas = $('canvas');
    map = new Map('<%= compute_public_path(@map.image.url, '') %>',
        canvas,
        MAX_X,
        MAX_Y,
        0, 0,
        0, 0,
        0, 0);
    map.drawStatic(function() {
    map.drawWifiLog(<%= @wifi_log.movement_log.manual_location.x %>,
    <%= @wifi_log.movement_log.manual_location.y %>,
    <%= @wifi_log.signal %>);
    });
  };
-->
</script>
<canvas id="canvas" width="500" height="300"></canvas>
<%- end -%>
<%- if !@map.nil? && (!@wifi_access_point.nil? || !@movement_log.nil?) -%>
<div id="wifi_logs">
<p id="notice"><%= notice %></p>

<p>
  <b>WifiAccessPoint:</b>
  <%= @wifi_log.wifi_access_point.mac %>
</p>

<p>
  <b>Devise:</b><br />
  user: <%= @wifi_log.movement_log.user.email %><br />
  user_agent: <%= @wifi_log.movement_log.user_agent %><br />
<p>

<p>
  <b>Location:</b><br />
  x: <%= @wifi_log.movement_log.manual_location.x %><br />
  y: <%= @wifi_log.movement_log.manual_location.y %><br />
  height: <%= @wifi_log.movement_log.manual_location.height %><br />
  time: <%= Time.at(@wifi_log.movement_log.manual_location.time/1000) %><br />
<p>

<p>
  <b>Signal:</b>
  <%= @wifi_log.signal %>
</p>
</div>
<%- end -%>

<div class="clear">
<%- if @map.nil? -%>
<%= link_to 'Back', maps_path %>
<%- elsif !@map.nil? && !@wifi_access_point.nil? -%>
<%= link_to 'Back', map_wifi_access_point_wifi_logs_path(:map_id => @map.id, :wifi_access_point_id => @wifi_access_point.id) %>
<%- elsif !@map.nil? && !@movement_log.nil? %>
<%= link_to 'Back', map_movement_log_wifi_logs_path(:map_id => @map.id, :movement_log_id => @movement_log.id) %>
<%- end -%>
</div>