config/routes.rb
WpsLogger::Application.routes.draw do
  devise_for :users

  resources :maps

  resources :maps do
    resources :wifi_access_points do
      resources :wifi_logs
    end
    resources :movement_logs do
      get 'index'
      resources :wifi_logs
    end
    resources :wifi_logs
    resources :maps
  end

  resources :manual_locations

  resources :gps_locations

  resources :wifi_access_points

  root :to => "welcome#index"

end

app/models/movement_log.rb
class MovementLog < ActiveRecord::Base
  belongs_to :gps_location
  belongs_to :manual_location
  belongs_to :user
  has_many :wifi_logs
  has_many :wifi_access_points, :through => :wifi_logs
end

app/models/wps_logger/movement_log.rb
class WpsLogger::MovementLog < WpsLogger::Base
  set_table_name :movement_logs

  belongs_to :gps_location
  belongs_to :manual_location
  belongs_to :user
  has_many :wifi_logs
end

app/controllers/movement_logs_controller.rb
class MovementLogsController < ApplicationController
  before_filter :authenticate_user!
  # GET /maps/1/movement_logs/
  def index
    if !params["map_id"].nil?
      @map = Map.find(params["map_id"])
    end
    if @map.nil?
      #FIXME
    else
      @movement_logs = MovementLog.where("manual_locations.map_id = ?", params[:map_id]).order("manual_locations.time").all(:include => [:manual_location])
    end
  end
end

app/helpers/movement_logs_helper.rb
module MovementLogsHelper
end

app/views/movement_logs/index.html.erb
<h1>Listing MovementLog</h1>

<%- if !@map.nil? -%>
<%= javascript_include_tag 'json2' %>
<%= javascript_include_tag 'map' %>
<script type="text/javascript">
  <!--
  // Global variables
  var map;
  var MAX_X = 800, MAX_Y = 640;

  window.onload = function () {
    var canvas = $('canvas');
    map = new Map('<%= compute_public_path(@map.image.url, '') %>',
        canvas,
        MAX_X,
        MAX_Y,
        0, 0,
        0, 0,
        0, 0);
    map.drawStatic(function() {
    <%- @movement_logs.each do |movement_log| -%>
      map.drawMovementLog(<%= movement_log.manual_location.x %>,
        <%= movement_log.manual_location.y %>);
    <%- end -%>
    });
  };
-->
</script>
<canvas id="canvas" width="500" height="300"></canvas>
<%- end -%>

<div id="movement_logs">
<table>
  <tr>
    <th colspan="2">Devise</th>
    <th colspan="4">Location</th>
    <th colspan="2">Operation</th>
  </tr>

<% @movement_logs.each do |movement_log| %>
  <tr>
    <td><%= movement_log.user.email %></td>
    <td><%= movement_log.user_agent %></td>
    <td><%= movement_log.manual_location.x %></td>
    <td><%= movement_log.manual_location.y %></td>
    <td><%= movement_log.manual_location.height %></td>
    <td><%= Time.at(movement_log.manual_location.time/1000) %></td>
    <td><%= link_to 'Show', map_movement_log_wifi_logs_path(:map_id => @map.id, :movement_log_id => movement_log.id) %></td>
    <td><%= link_to 'Destroy', map_movement_log_path(:map_id => @map.id, :id => movement_log.id), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>

<br />

<div class="clear">
<%= link_to 'Back', maps_path %>
</div>